config/routes.rb
Rails.application.routes.draw do
 
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get '/', to: 'home#index', as: 'home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :journals
  resources :goals
  resources :micro_goals
  resources :resources
end

app/views/resources/_form.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
body {
  background-color: lightblue;
}

h1 {
  color: black;
  text-align: center;
}

p {
  font-family: verdana;
  font-size: 20px;
  </style>
</head>
<body>



</body>
</html>

<%= form_for @resource do |f| %>
    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.all, :id, :username  %>
    <br>
    <%= f.label :website_domain %>
    <%= f.text_field :website_domain %>
    <br>
    <%= f.label :notes %>
    <%= f.text_area :notes%>
    <br>
    <%= f.submit%>
    <% end %>

app/views/resources/edit.html.erb
<h1>Edit Resources</h1>
<hr>
<%= render "form" %>
<br>
<%= form_for @resource, method: :delete do  | f | %>
    <%= f.submit "Delete" %>
<% end %>

app/views/resources/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
body {
  background-color: lightblue;
 
}

h1 {
  color: black;
  text-align: center;
}

p {
  font-family: verdana;
  font-size: 20px;
}
</style>
</head>
<body>


<h1>Click Name to View Suggested Resources </h1>
<hr>
<img src= "https://redeemer-charleston.org/wp-content/uploads/2014/11/books.jpg" >
<% @resources.each do |resource| %>
<h4>
<%=link_to resource.user.username, resource_path(resource)%>
</h4>
<%end%>
<h5><%= link_to "Create Resource Form", new_resource_path%></h5>

app/views/resources/new.html.erb
<h1> Create a New Resource Below! </h1>
<hr>
<%= render "form" %>

<%= link_to "Micro Goals", micro_goals_path %>
<br>
<%= link_to "User Page", users_path %>
    
   

app/views/resources/show.html.erb
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="style.css">
<style>
body {
  background-color: lightblue;
  
}

h1 {
  color: black;
  text-align: center;
}

p {
  font-family: verdana;
  font-size: 20px;
}
</style>
</head>
<body>


<h1> <%= @resource.user.username %>'s Suggested Resources </h1>
<hr>
<img src = "https://www.eclipsemediasolutions.com/sites/default/files/digital%20media%20icons.jpg" width="550" height="300">
<h4> Name: <%= @resource.user.username %>  </h4>
<h4> Website: <%= @resource.website_domain %>  </h4>
<a href="https://www.nutrisystem.com/jsps_hmr/home/index.jsp?gclid=CjwKCAiAouD_BRBIEiwALhJH6Be_D4mJPF4CJmZzmVGg2pHgDjUg1gNXaDs_5wOFJ6X5PWb57RixvxoCTbIQAvD_BwE&gclsrc=aw.ds" target="_blank"> How to Lose Weight Fast!</a>
<h4> Notes: <%= @resource.notes %>  </h4>

<%= link_to "List of Names", resources_path%>
<br>
<%= link_to "Edit Resource", edit_resource_path %>