config/routes.rb
Rails.application.routes.draw do
 
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get '/', to: 'home#index', as: 'home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :journals
  resources :goals
  resources :micro_goals
  resources :resources
end

app/models/journal.rb
class Journal < ApplicationRecord
    validates :name, presence: true
    validates :date, presence: true
    validates :title, presence: true
    validates :content, presence: true

    has_many :goals
    has_many :goals, through: :micro_goals
    belongs_to :user
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
    def index
        @journals = Journal.all
    end

    def show
        @journal = Journal.find(params[:id])
    end

    def new
        @journal = Journal.new
    end

    def create
        # @journal = Journal.create(journal_params)

        # redirect_to journals_path

        @journal = Journal.new(journal_params)

        if @journal.save
          redirect_to journal_path(@journal)
        else
          render :new
        end
    end

    def edit
        @journal = Journal.find(params[:id])
    end

    def update
        @journal = Journal.find_by(id: params[:id])
        if @journal.update(journal_params)
            redirect_to journal_path(@journal)
        else
            render :edit
        end
    end

    def destroy
        @journal = Journal.find_by(id: params[:id])
        @journal.delete

        redirect_to journals_path
    end

    private
    def journal_params
        params.require(:journal).permit(:name, :date, :title, :content, :user_id)
    end
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/journals/_form.html.erb
<%= form_for @journal do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :date %>
    <%= f.text_area :date %>

    <%= f.label :title %>
    <%= f.text_area :title %>

    <%= f.label :content %>
    <%= f.text_area :content %>
    
    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.all, :id, :username %>
    
    <%= f.submit %>
  <% end %>

app/views/journals/edit.html.erb
<h1>Edit Your Journal</h1>

<%= render 'form', goal: @journal %>

app/views/journals/index.html.erb
<h1>Hello User</h1> # want this header to greet the user by name

<ul>
<%@journals.each do | j |%>
    <li>
        <%= link_to j.title, journal_path(j)%>
    </li>
    <%end%>
</ul>
<%= link_to "Create Journal", new_journal_path%>

app/views/journals/new.html.erb
<h1>New Journal</h1>

<%= render 'form', journal: @journal %>

<%= link_to 'Back', journals_path %>

app/views/journals/show.html.erb
<h1>Welcome to <%= @journal.name%>'s Journal</h1>

<br/>

<h2>  <%= @journal.date %>  </h2>
<h2>  <%= @journal.title %>  </h2>
<h2>  <%= @journal.content %>  </h2>


<br/>
<%= link_to "Edit Journal", edit_journal_path%>
<%= link_to "All Journals", journals_path%>
<br/>
<%= form_for journal_path(@journal.id), method: "delete" do |f| %>
    <%= f.submit "Delete" %>
<% end %>
<br/>
<%= link_to "Create Goal", new_goal_path%>
<%= link_to "All Goals", goals_path%>