config/routes.rb
Rails.application.routes.draw do
 
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get '/', to: 'home#index', as: 'home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :journals
  resources :goals
  resources :micro_goals
  resources :resources
end

app/models/goal.rb
class Goal < ApplicationRecord
    has_many :micro_goals
    has_many :resources
    belongs_to :journal

    validates :name, presence: true
    validates :description, presence: true
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
    def index
        @goals = Goal.all
    end

    def show
        @goal = Goal.find(params[:id])
    end

    def new
        @goal = Goal.new
    end

    def create
        # @goal = Goal.create(goal_params)

        # redirect_to goals_path

        # Create a brand new, unsaved, not-yet-validated Post object from the form.
        @goal = Goal.new(goal_params)

        # Run the validations WITHOUT attempting to save to the database, returning
        # true if the Post is valid, and false if it's not.
        if @goal.valid?
            # If--and only if--the post is valid, do what we usually do.
            @goal.save
            # This returns a status_code of 302, which instructs the browser to
            # perform a NEW REQUEST! (AKA: throw @post away and let the show action
            # worry about re-reading it from the database)
            redirect_to goal_path(@goal)
        else
            # If the post is invalid, hold on to @post, because it is now full of
            # useful error messages, and re-render the :new page, which knows how
            # to display them alongside the user's entries.
            render :new
        end
    end

    def edit
        @goal = Goal.find(params[:id])
    end

    def update
        @goal = Goal.find_by(id: params[:id])
        if @goal.update(goal_params)
            redirect_to goal_path(@goal)
        else
            render :edit
        end
    end

    def destroy
        @goal = Goal.find_by(id: params[:id])
        @goal.delete

        redirect_to goals_path
    end

    private
    def goal_params
        params.require(:goal).permit(:name, :description, :journal_id)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<% if @goal.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@goal.errors.count, "error") %>
      prohibited this goal from being saved:
    </h2>

    <ul>
    <% @goal.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @goal do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :description %>
    <%= f.text_area :description %>
    
    <%= f.label :journal_id %>
    <%= f.collection_select :journal_id, Journal.all, :id, :name %>
    
    <%= f.submit %>
  <% end %>

app/views/goals/edit.html.erb
<h1>Edit Your Goals</h1>

<%= render 'form', goal: @goal %>

app/views/goals/index.html.erb
<h1>Hello</h1>

<ul>
<%@goals.each do | g |%>
    <li>
        <%= link_to g.name, goal_path(g)%>
    </li>
    <%end%>
</ul>

<%= link_to "Back", journals_path%>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= render 'form', goal: @goal %>

<%= link_to "Back", journals_path%>

app/views/goals/show.html.erb
<h1>A Goal</h1>

<br/>

<h2>  <%= @goal.name %>  </h2>
<h2>  <%= @goal.description %>  </h2>
<h2>  <%= @goal.journal_id %>  </h2>

<br/>
<%= link_to "Edit Goal", edit_goal_path%>
<%= link_to "Back", goals_path%>
<br/>
<%= form_for goal_path(@goal.id), method: "delete" do |f| %>
    <%= f.submit "Delete Goal" %>
<% end %>
<br/>
<%= link_to "All Micro-Goals", micro_goals_path%>
<%= link_to "All Resources", resources_path%>